FROM bitnami/minideb-runtimes:stretch
LABEL maintainer "Bitnami <containers@bitnami.com>"

RUN install_packages libxslt1.1 libtidy5 libmcrypt4 libldap-2.4-2 libpng16-16 libncurses5 libreadline7 libjpeg62-turbo libssl1.1 libcurl3 libfreetype6 libicu57
