FROM bitnami/minideb-runtimes:jessie
LABEL maintainer "Bitnami <containers@bitnami.com>"

RUN install_packages libxslt1.1 libtidy-0.99-0 libmcrypt4 libldap-2.4-2 libpng12-0 libjpeg62-turbo libssl1.0.0 libcurl3 libfreetype6 libicu52
